export type FactCategory =
  | "building_geometry"
  | "occupancy"
  | "escape"
  | "alarm_detection"
  | "active_fire"
  | "compartmentation"
  | "external_fire"
  | "firefighting"
  | "management"
  | "document_meta"
  | "other";

export type FactValueType =
  | "boolean"
  | "number"
  | "text"
  | "enum";

export type FactDefinition = {
  key: string;
  label: string;
  category: FactCategory;
  type: FactValueType;
  unit?: string;
  description?: string;
  aliases?: string[];
  examples?: string[];
};

function boolFact(
  key: string,
  label: string,
  category: FactCategory,
  extras: Partial<FactDefinition> = {}
): FactDefinition {
  return { key, label, category, type: "boolean", ...extras };
}

function numFact(
  key: string,
  label: string,
  category: FactCategory,
  unit?: string,
  extras: Partial<FactDefinition> = {}
): FactDefinition {
  return { key, label, category, type: "number", unit, ...extras };
}

function textFact(
  key: string,
  label: string,
  category: FactCategory,
  extras: Partial<FactDefinition> = {}
): FactDefinition {
  return { key, label, category, type: "text", ...extras };
}

function enumFact(
  key: string,
  label: string,
  category: FactCategory,
  examples: string[] = [],
  extras: Partial<FactDefinition> = {}
): FactDefinition {
  return { key, label, category, type: "enum", examples, ...extras };
}

export const FACT_ONTOLOGY: Record<string, FactDefinition> = {
  // ---------------------------------------------------------------------------
  // Building geometry
  // ---------------------------------------------------------------------------
  buildingHeightM: numFact("buildingHeightM", "Building height", "building_geometry", "m", {
    aliases: ["buildingHeightMeters", "buildingheightm"]
  }),
  buildingHeightMeters: numFact("buildingHeightMeters", "Building height", "building_geometry", "m"),
  buildingHeight_m: numFact("buildingHeight_m", "Building height", "building_geometry", "m"),

  topStoreyHeightM: numFact("topStoreyHeightM", "Top storey height", "building_geometry", "m", {
    aliases: ["heightTopStoreyM", "heightTopStorey_m", "height_top_storey_m", "topStoreyHeightMeters"]
  }),
  topStoreyHeightMeters: numFact("topStoreyHeightMeters", "Top storey height", "building_geometry", "m"),
  heightTopStoreyM: numFact("heightTopStoreyM", "Top storey height", "building_geometry", "m"),
  heightTopStorey_m: numFact("heightTopStorey_m", "Top storey height", "building_geometry", "m"),
  height_top_storey_m: numFact("height_top_storey_m", "Top storey height", "building_geometry", "m"),
  highestServedStoreyHeightM: numFact("highestServedStoreyHeightM", "Highest served storey height", "building_geometry", "m"),
  highestStoreyAboveGroundM: numFact("highestStoreyAboveGroundM", "Highest storey above ground", "building_geometry", "m"),
  flatStoreyHeightM: numFact("flatStoreyHeightM", "Flat storey height", "building_geometry", "m"),
  externalStairHeightAboveGroundM: numFact("externalStairHeightAboveGroundM", "External stair height above ground", "building_geometry", "m"),
  storeyHeightsM: textFact("storeyHeightsM", "Storey heights", "building_geometry"),

  storeys: numFact("storeys", "Number of storeys", "building_geometry", undefined, {
    aliases: ["storeyCount", "storeysCount", "numberOfStoreys"]
  }),
  storeyCount: numFact("storeyCount", "Number of storeys", "building_geometry"),
  storeyCountExcludingBasement: numFact("storeyCountExcludingBasement", "Storey count excluding basement", "building_geometry"),
  storeysAboveGroundCount: numFact("storeysAboveGroundCount", "Storeys above ground", "building_geometry"),
  storeysAboveGroundStorey: numFact("storeysAboveGroundStorey", "Storeys above ground storey", "building_geometry"),
  storeyIsGroundFlag: boolFact("storeyIsGroundFlag", "Storey is ground", "building_geometry"),
  storey: textFact("storey", "Storey", "building_geometry"),
  dwellingStorey: textFact("dwellingStorey", "Dwelling storey", "building_geometry"),

  internalFloorAreaM2: numFact("internalFloorAreaM2", "Internal floor area", "building_geometry", "m2"),
  areaM2: numFact("areaM2", "Area", "building_geometry", "m2"),
  area_m2: numFact("area_m2", "Area", "building_geometry", "m2"),
  roomFloorAreaM2: numFact("roomFloorAreaM2", "Room floor area", "building_geometry", "m2"),
  largestStoreyAreaM2: numFact("largestStoreyAreaM2", "Largest storey area", "building_geometry", "m2"),
  totalFloorAreaM2: numFact("totalFloorAreaM2", "Total floor area", "building_geometry", "m2"),
  panelAreaM2: numFact("panelAreaM2", "Panel area", "building_geometry", "m2"),
  panelArea_m2: numFact("panelArea_m2", "Panel area", "building_geometry", "m2"),

  boundaryDistanceMm: numFact("boundaryDistanceMm", "Boundary distance", "external_fire", "mm"),
  boundaryDistanceMeters: numFact("boundaryDistanceMeters", "Boundary distance", "external_fire", "m"),
  distanceToRelevantBoundaryMm: numFact("distanceToRelevantBoundaryMm", "Distance to relevant boundary", "external_fire", "mm"),
  distanceToRelevantBoundary_mm: numFact("distanceToRelevantBoundary_mm", "Distance to relevant boundary", "external_fire", "mm"),
  distanceToBoundaryM: numFact("distanceToBoundaryM", "Distance to boundary", "external_fire", "m"),
  distance_to_boundary_m: numFact("distance_to_boundary_m", "Distance to boundary", "external_fire", "m"),
  measuredDistanceToBoundaryMm: numFact("measuredDistanceToBoundaryMm", "Measured distance to boundary", "external_fire", "mm"),
  canopyProjectionM: numFact("canopyProjectionM", "Canopy projection", "external_fire", "m"),
  canopy_projection_m: numFact("canopy_projection_m", "Canopy projection", "external_fire", "m"),
  spandrelHeightMm: numFact("spandrelHeightMm", "Spandrel height", "external_fire", "mm"),
  minimumRequiredSpandrelHeightMm: numFact("minimumRequiredSpandrelHeightMm", "Minimum required spandrel height", "external_fire", "mm"),
  broofDistanceEachSideMm: numFact("broofDistanceEachSideMm", "BROOF distance each side", "external_fire", "mm"),
  wallAngleDeg: numFact("wallAngleDeg", "Wall angle", "external_fire", "deg"),
  wallAngle_deg: numFact("wallAngle_deg", "Wall angle", "external_fire", "deg"),
  unprotectedAreaM2: numFact("unprotectedAreaM2", "Unprotected area", "external_fire", "m2"),
  openingAreaM2: numFact("openingAreaM2", "Opening area", "external_fire", "m2"),
  calculatedMaxUnprotectedAreaM2: numFact("calculatedMaxUnprotectedAreaM2", "Calculated max unprotected area", "external_fire", "m2"),
  unprotectedAreaSeparationDistanceMm: numFact("unprotectedAreaSeparationDistanceMm", "Unprotected area separation distance", "external_fire", "mm"),

  maxRecessDepthM: numFact("maxRecessDepthM", "Maximum recess depth", "escape", "m"),
  max_recess_depth_m: numFact("max_recess_depth_m", "Maximum recess depth", "escape", "m"),
  minClearHeadroomMm: numFact("minClearHeadroomMm", "Minimum clear headroom", "escape", "mm"),
  minDistanceRouteToOpeningM: numFact("minDistanceRouteToOpeningM", "Minimum distance route to opening", "escape", "m"),

  // ---------------------------------------------------------------------------
  // Occupancy / use
  // ---------------------------------------------------------------------------
  purposeGroup: enumFact("purposeGroup", "Purpose group", "occupancy", ["1(a)", "2(a)", "2(b)", "3", "4", "5"]),
  purposeGroups: textFact("purposeGroups", "Purpose groups", "occupancy"),
  buildingUse: textFact("buildingUse", "Building use", "occupancy"),
  buildingType: textFact("buildingType", "Building type", "occupancy"),
  dwellingType: enumFact("dwellingType", "Dwelling type", "occupancy", ["flat", "dwellinghouse"]),
  hasFlats: boolFact("hasFlats", "Contains flats", "occupancy"),
  flatUnitFlag: boolFact("flatUnitFlag", "Flat unit", "occupancy"),
  isDwellingFlag: boolFact("isDwellingFlag", "Is dwelling", "occupancy"),
  sleepingAccommodation: boolFact("sleepingAccommodation", "Sleeping accommodation", "occupancy", {
    aliases: ["sleepingAccommodationFlag"]
  }),
  sleepingAccommodationFlag: boolFact("sleepingAccommodationFlag", "Sleeping accommodation", "occupancy"),
  hazardLevel: enumFact("hazardLevel", "Hazard level", "occupancy", ["normal", "higher"]),
  occupantLoad: numFact("occupantLoad", "Occupant load", "occupancy"),
  publicOccupancyLevel: textFact("publicOccupancyLevel", "Public occupancy level", "occupancy"),
  managedPopulationFlag: boolFact("managedPopulationFlag", "Managed population", "occupancy"),
  mixedUse: boolFact("mixedUse", "Mixed use", "occupancy"),
  mixedUseFlag: boolFact("mixedUseFlag", "Mixed use", "occupancy"),
  ancillaryToOtherUseFlag: boolFact("ancillaryToOtherUseFlag", "Ancillary to other use", "occupancy"),
  isFoodOrBarAreaFlag: boolFact("isFoodOrBarAreaFlag", "Food or bar area", "occupancy"),
  liveWorkUnitFlag: boolFact("liveWorkUnitFlag", "Live/work unit", "occupancy"),
  multiStoreyFlatFlag: boolFact("multiStoreyFlatFlag", "Multi-storey flat", "occupancy"),
  flatHasExternalEntranceAtGroundFlag: boolFact("flatHasExternalEntranceAtGroundFlag", "Flat has external entrance at ground", "occupancy"),
  roomType: textFact("roomType", "Room type", "occupancy"),
  spaceType: textFact("spaceType", "Space type", "occupancy"),
  spaceTypeBelowCeiling: textFact("spaceTypeBelowCeiling", "Space type below ceiling", "occupancy"),
  accessRoomType: textFact("accessRoomType", "Access room type", "occupancy"),
  accessRouteType: textFact("accessRouteType", "Access route type", "occupancy"),
  accessRouteType: textFact("accessRouteType", "Access route type", "occupancy"),
  carParkType: textFact("carParkType", "Car park type", "occupancy"),
  basementUse: textFact("basementUse", "Basement use", "occupancy"),
  garageType: textFact("garageType", "Garage type", "occupancy"),
  attachmentType: textFact("attachmentType", "Attachment type", "occupancy"),

  // ---------------------------------------------------------------------------
  // Escape / means of escape
  // ---------------------------------------------------------------------------
  numberOfStaircases: numFact("numberOfStaircases", "Number of staircases", "escape"),
  numberOfStairs: numFact("numberOfStairs", "Number of stairs", "escape"),
  commonStairCount: numFact("commonStairCount", "Common stair count", "escape"),
  stairCount: numFact("stairCount", "Stair count", "escape"),
  stairType: textFact("stairType", "Stair type", "escape"),
  stairWidthMm: numFact("stairWidthMm", "Stair width", "escape", "mm"),
  assignedOccupants: numFact("assignedOccupants", "Assigned occupants", "escape"),
  publicUseFlag: boolFact("publicUseFlag", "Public use", "escape"),
  compliesBS5395TypeEFlag: boolFact("compliesBS5395TypeEFlag", "Complies with BS 5395 Type E", "escape"),

  exitCount: numFact("exitCount", "Exit count", "escape"),
  finalExitCount: numFact("finalExitCount", "Final exit count", "escape"),
  storeyExitCount: numFact("storeyExitCount", "Storey exit count", "escape"),
  exitRequired: boolFact("exitRequired", "Exit required", "escape"),
  multipleFinalExitsRequired: boolFact("multipleFinalExitsRequired", "Multiple final exits required", "escape"),
  finalExitsIndependentFlag: boolFact("finalExitsIndependentFlag", "Final exits independent", "escape"),
  finalExitWidthMm: numFact("finalExitWidthMm", "Final exit width", "escape", "mm"),
  storeyExitWidthMm: numFact("storeyExitWidthMm", "Storey exit width", "escape", "mm"),
  exitWidthMm: numFact("exitWidthMm", "Exit width", "escape", "mm"),
  escapeRouteClearWidthMm: numFact("escapeRouteClearWidthMm", "Escape route clear width", "escape", "mm"),
  doorWidthMm: numFact("doorWidthMm", "Door width", "escape", "mm"),
  corridorWidthMm: numFact("corridorWidthMm", "Corridor width", "escape", "mm"),
  minApproachRouteWidthMm: numFact("minApproachRouteWidthMm", "Minimum approach route width", "escape", "mm"),
  finalExitLocation: textFact("finalExitLocation", "Final exit location", "escape"),
  final_exit_location: textFact("final_exit_location", "Final exit location", "escape"),

  travelDistanceSingleDirectionM: numFact("travelDistanceSingleDirectionM", "Single direction travel distance", "escape", "m"),
  singleDirectionDistM: numFact("singleDirectionDistM", "Single direction travel distance", "escape", "m"),
  singleDirectionTravelDistanceM: numFact("singleDirectionTravelDistanceM", "Single direction travel distance", "escape", "m"),
  singleDirectionDistanceM: numFact("singleDirectionDistanceM", "Single direction travel distance", "escape", "m"),
  travelDistanceTwoDirectionM: numFact("travelDistanceTwoDirectionM", "Two direction travel distance", "escape", "m"),
  travelDistanceNearestExitM: numFact("travelDistanceNearestExitM", "Travel distance to nearest exit", "escape", "m"),
  travelDistanceOneDirectionM: numFact("travelDistanceOneDirectionM", "Travel distance one direction", "escape", "m"),
  commonEscapeRouteTravelDistanceM: numFact("commonEscapeRouteTravelDistanceM", "Common escape route travel distance", "escape", "m"),
  commonEscapeTravelDistanceM: numFact("commonEscapeTravelDistanceM", "Common escape travel distance", "escape", "m"),
  commonCorridorTravelDistanceM: numFact("commonCorridorTravelDistanceM", "Common corridor travel distance", "escape", "m"),
  lobbyTravelDistanceM: numFact("lobbyTravelDistanceM", "Lobby travel distance", "escape", "m"),
  maxAllowedCommonEscapeRouteTravelDistanceM: numFact("maxAllowedCommonEscapeRouteTravelDistanceM", "Max allowed common escape route travel distance", "escape", "m"),
  maxAllowedCommonCorridorTravelDistanceM: numFact("maxAllowedCommonCorridorTravelDistanceM", "Max allowed common corridor travel distance", "escape", "m"),
  deadEndCorridorLengthM: numFact("deadEndCorridorLengthM", "Dead-end corridor length", "escape", "m"),
  maxDeadEndCorridorLengthM: numFact("maxDeadEndCorridorLengthM", "Maximum dead-end corridor length", "escape", "m"),
  deadEndAccessRouteLengthM: numFact("deadEndAccessRouteLengthM", "Dead-end access route length", "escape", "m"),

  twoDirectionsAvailableFlag: boolFact("twoDirectionsAvailableFlag", "Two directions of escape available", "escape"),
  alternativeEscapeRouteRequired: boolFact("alternativeEscapeRouteRequired", "Alternative escape route required", "escape"),
  alternativeEscapeRouteProvided: boolFact("alternativeEscapeRouteProvided", "Alternative escape route provided", "escape"),
  alternativeExitProvidedFlag: boolFact("alternativeExitProvidedFlag", "Alternative exit provided", "escape"),
  alternativeExitInBedroomPartFlag: boolFact("alternativeExitInBedroomPartFlag", "Alternative exit in bedroom part", "escape"),
  alternativeEscapeRoutesFromFootFlag: boolFact("alternativeEscapeRoutesFromFootFlag", "Alternative escape routes from stair foot", "escape"),
  servedBySingleCommonStairFlag: boolFact("servedBySingleCommonStairFlag", "Served by single common stair", "escape"),
  singleStairFlag: boolFact("singleStairFlag", "Single stair", "escape"),
  singleStairExceptionEligibleFlag: boolFact("singleStairExceptionEligibleFlag", "Single stair exception eligible", "escape"),
  singleStairJustificationProvidedFlag: boolFact("singleStairJustificationProvidedFlag", "Single stair justification provided", "escape"),
  commonEscapeRoutePresent: boolFact("commonEscapeRoutePresent", "Common escape route present", "escape"),
  commonCorridorPresent: boolFact("commonCorridorPresent", "Common corridor present", "escape"),
  commonLobbyPresent: boolFact("commonLobbyPresent", "Common lobby present", "escape"),
  deadEndCorridorPresent: boolFact("deadEndCorridorPresent", "Dead-end corridor present", "escape"),
  deadEndCommonCorridorFlag: boolFact("deadEndCommonCorridorFlag", "Dead-end common corridor", "escape"),
  deadEndAccessRouteFlag: boolFact("deadEndAccessRouteFlag", "Dead-end access route", "escape"),
  corridorSharedByMultipleOccupanciesFlag: boolFact("corridorSharedByMultipleOccupanciesFlag", "Corridor shared by multiple occupancies", "escape"),
  corridorHasRecessesFlag: boolFact("corridorHasRecessesFlag", "Corridor has recesses", "escape"),
  corridor_has_recesses_flag: boolFact("corridor_has_recesses_flag", "Corridor has recesses", "escape"),
  corridorWrapsBehindStairFlag: boolFact("corridorWrapsBehindStairFlag", "Corridor wraps behind stair", "escape"),
  corridor_wraps_behind_stair_flag: boolFact("corridor_wraps_behind_stair_flag", "Corridor wraps behind stair", "escape"),
  corridorEnclosurePresentFlag: boolFact("corridorEnclosurePresentFlag", "Corridor enclosure present", "escape"),
  corridorIsProtected: boolFact("corridorIsProtected", "Corridor is protected", "escape"),
  protectedCorridorFlag: boolFact("protectedCorridorFlag", "Protected corridor", "escape"),
  protectedCorridorRequired: boolFact("protectedCorridorRequired", "Protected corridor required", "escape"),
  protectedCorridorProvided: boolFact("protectedCorridorProvided", "Protected corridor provided", "escape"),
  protectedStairFlag: boolFact("protectedStairFlag", "Protected stair", "escape"),
  protectedStairPresentFlag: boolFact("protectedStairPresentFlag", "Protected stair present", "escape"),
  protectedStairProvided: boolFact("protectedStairProvided", "Protected stair provided", "escape"),
  protectedStairProvidedFlag: boolFact("protectedStairProvidedFlag", "Protected stair provided", "escape"),
  protectedStairOrEntranceHallPresent: boolFact("protectedStairOrEntranceHallPresent", "Protected stair or entrance hall present", "escape"),
  protectedRoutePresentFlag: boolFact("protectedRoutePresentFlag", "Protected route present", "escape"),
  protectedAreasCount: numFact("protectedAreasCount", "Protected areas count", "escape"),
  lobbyToStairRequired: boolFact("lobbyToStairRequired", "Lobby to stair required", "escape"),
  lobbyToStairProvided: boolFact("lobbyToStairProvided", "Lobby to stair provided", "escape"),
  lobbyOmitted: boolFact("lobbyOmitted", "Lobby omitted", "escape"),
  routePassesThroughStairEnclosure: boolFact("routePassesThroughStairEnclosure", "Route passes through stair enclosure", "escape"),
  routeSegmentType: textFact("routeSegmentType", "Route segment type", "escape"),
  route_segment_type: textFact("route_segment_type", "Route segment type", "escape"),
  routeLeadsToExitFlag: boolFact("routeLeadsToExitFlag", "Route leads to exit", "escape"),
  routeLeadsToStoreyExitOrExternalRouteFlag: boolFact("routeLeadsToStoreyExitOrExternalRouteFlag", "Route leads to storey exit or external route", "escape"),
  routeFromFootToSafetyWithin1800mmRE30ProvidedFlag: boolFact("routeFromFootToSafetyWithin1800mmRE30ProvidedFlag", "Route from stair foot to safety within 1800mm RE30 provided", "escape"),
  escapeRoutePresent: boolFact("escapeRoutePresent", "Escape route present", "escape"),
  escapeRoutePresentFlag: boolFact("escapeRoutePresentFlag", "Escape route present", "escape"),
  escape_route_present_flag: boolFact("escape_route_present_flag", "Escape route present", "escape"),
  escapeRouteUsesFlatRoof: boolFact("escapeRouteUsesFlatRoof", "Escape route uses flat roof", "escape"),
  escapeRouteOverFlatRoofFlag: boolFact("escapeRouteOverFlatRoofFlag", "Escape route over flat roof", "escape"),
  escapeRouteWithin4_5mOfOpeningFlag: boolFact("escapeRouteWithin4_5mOfOpeningFlag", "Escape route within 4.5m of opening", "escape"),
  openConnectionPresent: boolFact("openConnectionPresent", "Open connection present", "escape"),
  openingBetweenFloorsPresentFlag: boolFact("openingBetweenFloorsPresentFlag", "Opening between floors present", "escape"),
  hasInternalFloorOpeningFlag: boolFact("hasInternalFloorOpeningFlag", "Internal floor opening present", "escape"),
  requiresRefugesFlag: boolFact("requiresRefugesFlag", "Refuges required", "escape"),

  onEscapeRouteFlag: boolFact("onEscapeRouteFlag", "On escape route", "escape"),
  on_escape_route_flag: boolFact("on_escape_route_flag", "On escape route", "escape"),
  hardwareType: textFact("hardwareType", "Hardware type", "escape"),
  securityLockType: textFact("securityLockType", "Security lock type", "escape"),
  doorSwingDirection: textFact("doorSwingDirection", "Door swing direction", "escape"),
  doorLocation: textFact("doorLocation", "Door location", "escape"),
  door_location: textFact("door_location", "Door location", "escape"),
  doorDividesCorridor: boolFact("doorDividesCorridor", "Door divides corridor", "escape"),
  doorSwingsBothWays: boolFact("doorSwingsBothWays", "Door swings both ways", "escape"),
  doorHasVisionPanel: boolFact("doorHasVisionPanel", "Door has vision panel", "escape"),
  doorOpensOntoCorridorOrStair: boolFact("doorOpensOntoCorridorOrStair", "Door opens onto corridor or stair", "escape"),
  hasRevolvingDoor: boolFact("hasRevolvingDoor", "Revolving door present", "escape"),
  hasAutomaticDoor: boolFact("hasAutomaticDoor", "Automatic door present", "escape"),
  hasTurnstile: boolFact("hasTurnstile", "Turnstile present", "escape"),
  isMainEntranceFlag: boolFact("isMainEntranceFlag", "Is main entrance", "escape"),
  is_main_entrance_flag: boolFact("is_main_entrance_flag", "Is main entrance", "escape"),
  exitSignPresentFlag: boolFact("exitSignPresentFlag", "Exit sign present", "escape"),
  exit_sign_present_flag: boolFact("exit_sign_present_flag", "Exit sign present", "escape"),
  signStandardCompliantFlag: boolFact("signStandardCompliantFlag", "Sign standard compliant", "escape"),
  sign_standard_compliant_flag: boolFact("sign_standard_compliant_flag", "Sign standard compliant", "escape"),

  innerRoomFlag: boolFact("innerRoomFlag", "Inner room", "escape"),
  innerInnerRoomFlag: boolFact("innerInnerRoomFlag", "Inner-inner room", "escape"),
  roomIsInnerRoomFlag: boolFact("roomIsInnerRoomFlag", "Room is inner room", "escape"),
  roomIsInnerInnerRoomFlag: boolFact("roomIsInnerInnerRoomFlag", "Room is inner-inner room", "escape"),
  visionPanelsOrOpenHeadFlag: boolFact("visionPanelsOrOpenHeadFlag", "Vision panels or open head provided", "escape"),
  smokeDetectionInAccessRoom: boolFact("smokeDetectionInAccessRoom", "Smoke detection in access room", "escape"),

  emergencyEscapeWindowPresent: boolFact("emergencyEscapeWindowPresent", "Emergency escape window present", "escape"),
  emergencyEscapeWindowProvidedFlag: boolFact("emergencyEscapeWindowProvidedFlag", "Emergency escape window provided", "escape"),
  emergencyEscapeDoorProvidedFlag: boolFact("emergencyEscapeDoorProvidedFlag", "Emergency escape door provided", "escape"),
  escapeWindowProvidedFlag: boolFact("escapeWindowProvidedFlag", "Escape window provided", "escape"),
  hasEscapeWindowFlag: boolFact("hasEscapeWindowFlag", "Has escape window", "escape"),
  escapeWindowClearOpenAreaM2: numFact("escapeWindowClearOpenAreaM2", "Escape window clear open area", "escape", "m2"),
  escapeWindowMinDimensionMm: numFact("escapeWindowMinDimensionMm", "Escape window minimum dimension", "escape", "mm"),
  escapeWindowSillHeightMm: numFact("escapeWindowSillHeightMm", "Escape window sill height", "escape", "mm"),
  replacementWindowClearOpenableAreaM2: numFact("replacementWindowClearOpenableAreaM2", "Replacement window clear openable area", "escape", "m2"),
  replacementWindowsFlag: boolFact("replacementWindowsFlag", "Replacement windows", "escape"),
  existingEscapeWindowFlag: boolFact("existingEscapeWindowFlag", "Existing escape window", "escape"),
  existingDwellingFlag: boolFact("existingDwellingFlag", "Existing dwelling", "escape"),
  habitableRoomAtGroundStoreyFlag: boolFact("habitableRoomAtGroundStoreyFlag", "Habitable room at ground storey", "escape"),
  habitableRoomFlag: boolFact("habitableRoomFlag", "Habitable room", "escape"),
  basementHabitableRoomsFlag: boolFact("basementHabitableRoomsFlag", "Basement habitable rooms", "escape"),
  basementsWithHabitableRoomsFlag: boolFact("basementsWithHabitableRoomsFlag", "Basements with habitable rooms", "escape"),
  loftConversionFlag: boolFact("loftConversionFlag", "Loft conversion", "escape"),
  galleryPresent: boolFact("galleryPresent", "Gallery present", "escape"),
  galleryPresentFlag: boolFact("galleryPresentFlag", "Gallery present", "escape"),
  sameBuildingFlag: boolFact("sameBuildingFlag", "Same building", "escape"),
  hasDirectHallAccess: boolFact("hasDirectHallAccess", "Has direct hall access", "escape"),

  externalStairFlag: boolFact("externalStairFlag", "External stair", "escape"),
  externalEscapeStairPresent: boolFact("externalEscapeStairPresent", "External escape stair present", "escape"),
  externalEscapeStairProvidedFlag: boolFact("externalEscapeStairProvidedFlag", "External escape stair provided", "escape"),
  escapeStairPresentFlag: boolFact("escapeStairPresentFlag", "Escape stair present", "escape"),
  escape_stair_present_flag: boolFact("escape_stair_present_flag", "Escape stair present", "escape"),
  escapeStairRequired: boolFact("escapeStairRequired", "Escape stair required", "escape"),
  escapeStairProvided: boolFact("escapeStairProvided", "Escape stair provided", "escape"),
  doorsToStairE30Flag: boolFact("doorsToStairE30Flag", "Doors to stair E30", "escape"),
  doorsToStairSelfClosingFlag: boolFact("doorsToStairSelfClosingFlag", "Doors to stair self-closing", "escape"),
  envelopeRE30ZonesProvidedFlag: boolFact("envelopeRE30ZonesProvidedFlag", "Envelope RE30 zones provided", "escape"),
  glazingInFRZonesFixedShutFlag: boolFact("glazingInFRZonesFixedShutFlag", "Glazing in fire-resisting zones fixed shut", "escape"),
  glazingInFRZonesE30Flag: boolFact("glazingInFRZonesE30Flag", "Glazing in fire-resisting zones E30", "escape"),
  stairProjectsBeyondExternalWallFlag: boolFact("stairProjectsBeyondExternalWallFlag", "Stair projects beyond external wall", "escape"),
  stairRecessedFromExternalWallFlag: boolFact("stairRecessedFromExternalWallFlag", "Stair recessed from external wall", "escape"),
  stairInInternalFacadeAngleFlag: boolFact("stairInInternalFacadeAngleFlag", "Stair in internal facade angle", "escape"),
  electricMeterInStairFlag: boolFact("electricMeterInStairFlag", "Electric meter in stair", "escape"),
  electric_meter_in_stair_flag: boolFact("electric_meter_in_stair_flag", "Electric meter in stair", "escape"),
  combustibleStoragePresentFlag: boolFact("combustibleStoragePresentFlag", "Combustible storage present", "escape"),
  gasServicesInStairFlag: boolFact("gasServicesInStairFlag", "Gas services in stair", "escape"),
  gasPipeFireStoppedFlag: boolFact("gasPipeFireStoppedFlag", "Gas pipe fire-stopped", "escape"),
  hasRefuseChuteOrStorageFlag: boolFact("hasRefuseChuteOrStorageFlag", "Refuse chute or storage present", "escape"),
  has_refuse_chute_or_storage_flag: boolFact("has_refuse_chute_or_storage_flag", "Refuse chute or storage present", "escape"),
  isWalkInStoreFlag: boolFact("isWalkInStoreFlag", "Walk-in store", "escape"),
  is_walk_in_store_flag: boolFact("is_walk_in_store_flag", "Walk-in store", "escape"),
  servesPublicAreaFlag: boolFact("servesPublicAreaFlag", "Serves public area", "escape"),
  servesPlantRoomOnlyFlag: boolFact("servesPlantRoomOnlyFlag", "Serves plant room only", "escape"),
  usesWithinStairList: textFact("usesWithinStairList", "Uses within stair list", "escape"),

  // ---------------------------------------------------------------------------
  // Alarm / detection / active fire
  // ---------------------------------------------------------------------------
  fireAlarmSystem: textFact("fireAlarmSystem", "Fire alarm system", "alarm_detection"),
  alarmSystemType: textFact("alarmSystemType", "Alarm system type", "alarm_detection"),
  alarmCategory: enumFact("alarmCategory", "Alarm category", "alarm_detection", ["L1", "L2", "L3", "L4", "L5", "LD1", "LD2", "LD3", "P1", "P2"]),
  alarmGrade: enumFact("alarmGrade", "Alarm grade", "alarm_detection", ["A", "B", "C", "D1", "D2"]),
  domesticAlarmGrade: enumFact("domesticAlarmGrade", "Domestic alarm grade", "alarm_detection", ["A", "D1", "D2"]),
  domesticAlarmCategory: enumFact("domesticAlarmCategory", "Domestic alarm category", "alarm_detection", ["LD1", "LD2", "LD3"]),
  alarmSystemPresentFlag: boolFact("alarmSystemPresentFlag", "Alarm system present", "alarm_detection"),
  alarmSystemExtendedFlag: boolFact("alarmSystemExtendedFlag", "Alarm system extended", "alarm_detection"),
  commonAlarmPresentFlag: boolFact("commonAlarmPresentFlag", "Common alarm present", "alarm_detection"),
  automaticDetectionPresent: boolFact("automaticDetectionPresent", "Automatic detection present", "alarm_detection"),
  automaticDetectionProvided: boolFact("automaticDetectionProvided", "Automatic detection provided", "alarm_detection"),
  automaticDetectionAlarmRequired: boolFact("automaticDetectionAlarmRequired", "Automatic detection and alarm required", "alarm_detection"),
  voiceAlarmPresent: boolFact("voiceAlarmPresent", "Voice alarm present", "alarm_detection"),
  voiceAlarmBs5839_8_ComplianceEvidence: textFact("voiceAlarmBs5839_8_ComplianceEvidence", "Voice alarm BS 5839-8 compliance evidence", "alarm_detection"),
  bs5839_1_ComplianceEvidence: textFact("bs5839_1_ComplianceEvidence", "BS 5839-1 compliance evidence", "alarm_detection"),
  alarmSoundersAllAreas: boolFact("alarmSoundersAllAreas", "Alarm sounders in all areas", "alarm_detection"),
  stagedAlarmPresent: boolFact("stagedAlarmPresent", "Staged alarm present", "alarm_detection"),
  emergencyLightingPresent: boolFact("emergencyLightingPresent", "Emergency lighting present", "active_fire"),
  emergency_lighting_present_flag: boolFact("emergency_lighting_present_flag", "Emergency lighting present", "active_fire"),
  smokeVentilationRequired: boolFact("smokeVentilationRequired", "Smoke ventilation required", "active_fire"),
  smokeVentilationProvided: boolFact("smokeVentilationProvided", "Smoke ventilation provided", "active_fire"),
  aovProvided: boolFact("aovProvided", "Automatic opening vent provided", "active_fire"),
  smokeControlProvided: boolFact("smokeControlProvided", "Smoke control provided", "active_fire"),
  smokeControlSystemRequired: boolFact("smokeControlSystemRequired", "Smoke control system required", "active_fire"),
  smokeControlSystemProvided: boolFact("smokeControlSystemProvided", "Smoke control system provided", "active_fire"),
  smokeControlSystemType: textFact("smokeControlSystemType", "Smoke control system type", "active_fire"),
  sprinklerSystemPresent: boolFact("sprinklerSystemPresent", "Sprinkler system present", "active_fire"),
  sprinklersProvided: boolFact("sprinklersProvided", "Sprinklers provided", "active_fire"),
  sprinklersPresent: boolFact("sprinklersPresent", "Sprinklers present", "active_fire"),
  hasSprinklerSystem: boolFact("hasSprinklerSystem", "Has sprinkler system", "active_fire"),
  evacAlertSystemProvided: boolFact("evacAlertSystemProvided", "Evacuation alert system provided", "active_fire"),

  // ---------------------------------------------------------------------------
  // Firefighting
  // ---------------------------------------------------------------------------
  fireMainsPresent: boolFact("fireMainsPresent", "Fire mains present", "firefighting"),
  fireMainsProvided: boolFact("fireMainsProvided", "Fire mains provided", "firefighting"),
  fireMainsProvidedFlag: boolFact("fireMainsProvidedFlag", "Fire mains provided", "firefighting"),
  fireMainPresent: boolFact("fireMainPresent", "Fire main present", "firefighting"),
  fireMainRequired: boolFact("fireMainRequired", "Fire main required", "firefighting"),
  fireMainProvided: boolFact("fireMainProvided", "Fire main provided", "firefighting"),
  fireMainInletAccessible: boolFact("fireMainInletAccessible", "Fire main inlet accessible", "firefighting"),
  dryRiserPresent: boolFact("dryRiserPresent", "Dry riser present", "firefighting"),
  dryFireMainProvidedFlag: boolFact("dryFireMainProvidedFlag", "Dry fire main provided", "firefighting"),
  dryRiserInletSignageVisible: boolFact("dryRiserInletSignageVisible", "Dry riser inlet signage visible", "firefighting"),
  landingValveClearanceCompliant: boolFact("landingValveClearanceCompliant", "Landing valve clearance compliant", "firefighting"),
  fireServiceAccessDistanceM: numFact("fireServiceAccessDistanceM", "Fire service access distance", "firefighting", "m"),
  fireEngineAccessDistanceM: numFact("fireEngineAccessDistanceM", "Fire engine access distance", "firefighting", "m"),
  fireServiceVehicleAccessProvided: boolFact("fireServiceVehicleAccessProvided", "Fire service vehicle access provided", "firefighting"),
  fireServiceAccessProvided: boolFact("fireServiceAccessProvided", "Fire service access provided", "firefighting"),
  requiresApplianceAccess: boolFact("requiresApplianceAccess", "Requires appliance access", "firefighting"),
  pumpApplianceAccessRequired: boolFact("pumpApplianceAccessRequired", "Pump appliance access required", "firefighting"),
  pumpApplianceAccessProvided: boolFact("pumpApplianceAccessProvided", "Pump appliance access provided", "firefighting"),
  hoseDistanceMeters: numFact("hoseDistanceMeters", "Hose distance", "firefighting", "m"),
  maxHosePathLengthM: numFact("maxHosePathLengthM", "Maximum hose path length", "firefighting", "m"),
  hoseDistanceMaxM: numFact("hoseDistanceMaxM", "Maximum hose distance", "firefighting", "m"),
  hoseDistanceMax_m: numFact("hoseDistanceMax_m", "Maximum hose distance", "firefighting", "m"),
  hoseCoverageAllAreas: boolFact("hoseCoverageAllAreas", "Hose coverage all areas", "firefighting"),
  maxStoreyAboveFRSAccessLevelM: numFact("maxStoreyAboveFRSAccessLevelM", "Max storey above FRS access level", "firefighting", "m"),
  pumpingApplianceDistanceToInletM: numFact("pumpingApplianceDistanceToInletM", "Pumping appliance distance to inlet", "firefighting", "m"),

  hydrantDistanceM: numFact("hydrantDistanceM", "Hydrant distance", "firefighting", "m"),
  distanceToNearestPublicHydrantM: numFact("distanceToNearestPublicHydrantM", "Distance to nearest public hydrant", "firefighting", "m"),
  privateHydrantsProvided: boolFact("privateHydrantsProvided", "Private hydrants provided", "firefighting"),
  hardstandingProvided: boolFact("hardstandingProvided", "Hardstanding provided", "firefighting"),

  firefightingShaftRequired: boolFact("firefightingShaftRequired", "Firefighting shaft required", "firefighting"),
  firefightingShaftPresent: boolFact("firefightingShaftPresent", "Firefighting shaft present", "firefighting"),
  firefightingShaftProvided: boolFact("firefightingShaftProvided", "Firefighting shaft provided", "firefighting"),
  firefightingShaftProvidedFlag: boolFact("firefightingShaftProvidedFlag", "Firefighting shaft provided", "firefighting"),
  protectedShaftProvidedFlag: boolFact("protectedShaftProvidedFlag", "Protected shaft provided", "firefighting"),
  protectedShaft: boolFact("protectedShaft", "Protected shaft", "firefighting"),
  firefightingLiftRequired: boolFact("firefightingLiftRequired", "Firefighting lift required", "firefighting"),
  firefightingLiftProvided: boolFact("firefightingLiftProvided", "Firefighting lift provided", "firefighting"),
  firefightingLobbyProvided: boolFact("firefightingLobbyProvided", "Firefighting lobby provided", "firefighting"),
  secureInformationBoxProvided: boolFact("secureInformationBoxProvided", "Secure information box provided", "firefighting"),
  wayfindingSignageProvided: boolFact("wayfindingSignageProvided", "Wayfinding signage provided", "firefighting"),
  liftStandard: textFact("liftStandard", "Lift standard", "firefighting"),
  storeyHeightMaxM: numFact("storeyHeightMaxM", "Storey height maximum", "firefighting", "m"),
  storeyHeightMax_m: numFact("storeyHeightMax_m", "Storey height maximum", "firefighting", "m"),

  // ---------------------------------------------------------------------------
  // Compartmentation / structure
  // ---------------------------------------------------------------------------
  fireResistanceMinutes: numFact("fireResistanceMinutes", "Fire resistance", "compartmentation", "minutes"),
  requiredFireResistanceMinutes: numFact("requiredFireResistanceMinutes", "Required fire resistance", "compartmentation", "minutes"),
  providedFireResistanceMinutes: numFact("providedFireResistanceMinutes", "Provided fire resistance", "compartmentation", "minutes"),
  requiredCompartmentFireResistanceMinutes: numFact("requiredCompartmentFireResistanceMinutes", "Required compartment fire resistance", "compartmentation", "minutes"),
  compartmentElementFireResistanceMinutes: numFact("compartmentElementFireResistanceMinutes", "Compartment element fire resistance", "compartmentation", "minutes"),
  compartmentFloorFireResistanceMin: numFact("compartmentFloorFireResistanceMin", "Compartment floor fire resistance", "compartmentation", "minutes"),
  compartmentWallFireResistanceMin: numFact("compartmentWallFireResistanceMin", "Compartment wall fire resistance", "compartmentation", "minutes"),
  floorFireResistanceMin: numFact("floorFireResistanceMin", "Floor fire resistance", "compartmentation", "minutes"),
  shaftEnclosureFireResistanceMin: numFact("shaftEnclosureFireResistanceMin", "Shaft enclosure fire resistance", "compartmentation", "minutes"),
  shaftEnclosureFireResistanceMinutes: numFact("shaftEnclosureFireResistanceMinutes", "Shaft enclosure fire resistance", "compartmentation", "minutes"),
  riserEnclosureFireResistanceMin: numFact("riserEnclosureFireResistanceMin", "Riser enclosure fire resistance", "compartmentation", "minutes"),
  openingFireResistanceMin: numFact("openingFireResistanceMin", "Opening fire resistance", "compartmentation", "minutes"),
  doorFireRatingMinutes: numFact("doorFireRatingMinutes", "Door fire rating", "compartmentation", "minutes"),
  flueOrDuctWallFireResistanceMinutes: numFact("flueOrDuctWallFireResistanceMinutes", "Flue or duct wall fire resistance", "compartmentation", "minutes"),
  elementFireResistanceMinutes: numFact("elementFireResistanceMinutes", "Element fire resistance", "compartmentation", "minutes"),
  elementFrMinutes: numFact("elementFrMinutes", "Element fire resistance", "compartmentation", "minutes"),
  supportingElementFireResistanceMinutes: numFact("supportingElementFireResistanceMinutes", "Supporting element fire resistance", "compartmentation", "minutes"),
  supportedElementFireResistanceMinutes: numFact("supportedElementFireResistanceMinutes", "Supported element fire resistance", "compartmentation", "minutes"),
  supportingFireResistanceMinutes: numFact("supportingFireResistanceMinutes", "Supporting fire resistance", "compartmentation", "minutes"),
  supportedFireResistanceMinutes: numFact("supportedFireResistanceMinutes", "Supported fire resistance", "compartmentation", "minutes"),
  ceilingFireResistanceEIMinutes: numFact("ceilingFireResistanceEIMinutes", "Ceiling fire resistance EI", "compartmentation", "minutes"),
  existingFirstStoreyRMinutes: numFact("existingFirstStoreyRMinutes", "Existing first storey R minutes", "compartmentation", "minutes"),
  newFloorFireResistanceMinutes: numFact("newFloorFireResistanceMinutes", "New floor fire resistance", "compartmentation", "minutes"),

  largestCompartmentAreaM2: numFact("largestCompartmentAreaM2", "Largest compartment area", "compartmentation", "m2"),
  compartmentFloorAreaM2: numFact("compartmentFloorAreaM2", "Compartment floor area", "compartmentation", "m2"),
  compartmentSizeM2: numFact("compartmentSizeM2", "Compartment size", "compartmentation", "m2"),
  maxAllowedCompartmentAreaM2: numFact("maxAllowedCompartmentAreaM2", "Maximum allowed compartment area", "compartmentation", "m2"),

  compartmentationRequired: boolFact("compartmentationRequired", "Compartmentation required", "compartmentation"),
  compartmentFloorRequired: boolFact("compartmentFloorRequired", "Compartment floor required", "compartmentation"),
  compartmentFloorProvided: boolFact("compartmentFloorProvided", "Compartment floor provided", "compartmentation"),
  compartmentFloorPresent: boolFact("compartmentFloorPresent", "Compartment floor present", "compartmentation"),
  compartmentWallRequired: boolFact("compartmentWallRequired", "Compartment wall required", "compartmentation"),
  compartmentWallProvided: boolFact("compartmentWallProvided", "Compartment wall provided", "compartmentation"),
  compartmentWallPresent: boolFact("compartmentWallPresent", "Compartment wall present", "compartmentation"),
  compartmentWallThroughRoofFlag: boolFact("compartmentWallThroughRoofFlag", "Compartment wall through roof", "compartmentation"),
  compartmentWallMeetsRoofFlag: boolFact("compartmentWallMeetsRoofFlag", "Compartment wall meets roof", "compartmentation"),
  compartmentWallMeetsOrPassesUnderRoofFlag: boolFact("compartmentWallMeetsOrPassesUnderRoofFlag", "Compartment wall meets or passes under roof", "compartmentation"),
  compartmentLineContinuesThroughVoid: boolFact("compartmentLineContinuesThroughVoid", "Compartment line continues through void", "compartmentation"),
  compartmentationContinuousAtJunction: boolFact("compartmentationContinuousAtJunction", "Compartmentation continuous at junction", "compartmentation"),
  compartmentationJunctionPresent: boolFact("compartmentationJunctionPresent", "Compartmentation junction present", "compartmentation"),
  isCompartmentJunction: boolFact("isCompartmentJunction", "Is compartment junction", "compartmentation"),
  compartmentRole: textFact("compartmentRole", "Compartment role", "compartmentation"),
  wallType: textFact("wallType", "Wall type", "compartmentation"),
  runsFullHeight: boolFact("runsFullHeight", "Runs full height", "compartmentation"),
  treatedAsSeparatedPart: boolFact("treatedAsSeparatedPart", "Treated as separated part", "compartmentation"),
  wallExtendsFullHeight: boolFact("wallExtendsFullHeight", "Wall extends full height", "compartmentation"),
  separateCompartmentsBetweenUses: boolFact("separateCompartmentsBetweenUses", "Separate compartments between uses", "compartmentation"),
  useAbove: textFact("useAbove", "Use above", "compartmentation"),
  useBelow: textFact("useBelow", "Use below", "compartmentation"),

  servicePenetrationsPresent: boolFact("servicePenetrationsPresent", "Service penetrations present", "compartmentation"),
  penetratesFireResistingElement: boolFact("penetratesFireResistingElement", "Penetrates fire-resisting element", "compartmentation"),
  penetratesCompartmentWallOrFloor: boolFact("penetratesCompartmentWallOrFloor", "Penetrates compartment wall or floor", "compartmentation"),
  fireStoppingPresent: boolFact("fireStoppingPresent", "Fire stopping present", "compartmentation"),
  fireStoppingProvided: boolFact("fireStoppingProvided", "Fire stopping provided", "compartmentation"),
  firestoppingPresent: boolFact("firestoppingPresent", "Fire stopping present", "compartmentation"),
  fire_stopping_present: boolFact("fire_stopping_present", "Fire stopping present", "compartmentation"),
  fireStoppingContinuousFullWallThickness: boolFact("fireStoppingContinuousFullWallThickness", "Fire stopping continuous full wall thickness", "compartmentation"),
  fireStoppingToUndersideOfRoofCovering: boolFact("fireStoppingToUndersideOfRoofCovering", "Fire stopping to underside of roof covering", "compartmentation"),
  fireStoppingToUndersideOfRoofCoveringAtWallFlag: boolFact("fireStoppingToUndersideOfRoofCoveringAtWallFlag", "Fire stopping to underside of roof covering at wall", "compartmentation"),
  fireSeparatingElementPresent: boolFact("fireSeparatingElementPresent", "Fire separating element present", "compartmentation"),
  jointsOrGapsPresent: boolFact("jointsOrGapsPresent", "Joints or gaps present", "compartmentation"),
  serviceOpeningsPresent: boolFact("serviceOpeningsPresent", "Service openings present", "compartmentation"),
  servicesPresent: boolFact("servicesPresent", "Services present", "compartmentation"),
  voidContinuous: boolFact("voidContinuous", "Void continuous", "compartmentation"),
  serviceRiserPresent: boolFact("serviceRiserPresent", "Service riser present", "compartmentation"),
  riserCrossesCompartments: boolFact("riserCrossesCompartments", "Riser crosses compartments", "compartmentation"),
  shaftOpeningsPresent: boolFact("shaftOpeningsPresent", "Shaft openings present", "compartmentation"),
  hasLiftShaft: boolFact("hasLiftShaft", "Lift shaft present", "compartmentation"),
  ductPenetrationsPresent: boolFact("ductPenetrationsPresent", "Duct penetrations present", "compartmentation"),
  ductPenetratesCompartmentBoundary: boolFact("ductPenetratesCompartmentBoundary", "Duct penetrates compartment boundary", "compartmentation"),
  fireDamperPresent: boolFact("fireDamperPresent", "Fire damper present", "compartmentation"),
  penetrationGapPresent: boolFact("penetrationGapPresent", "Penetration gap present", "compartmentation"),
  gapSealed: boolFact("gapSealed", "Gap sealed", "compartmentation"),
  openingSizeMinimised: boolFact("openingSizeMinimised", "Opening size minimised", "compartmentation"),
  proprietarySealUsed: boolFact("proprietarySealUsed", "Proprietary seal used", "compartmentation"),
  sealTestedToMaintainFireResistance: boolFact("sealTestedToMaintainFireResistance", "Seal tested to maintain fire resistance", "compartmentation"),

  cavityPresent: boolFact("cavityPresent", "Cavity present", "compartmentation"),
  cavityPresentFlag: boolFact("cavityPresentFlag", "Cavity present", "compartmentation"),
  concealedCavitiesPresentFlag: boolFact("concealedCavitiesPresentFlag", "Concealed cavities present", "compartmentation"),
  cavityAboveCorridorEnclosureFlag: boolFact("cavityAboveCorridorEnclosureFlag", "Cavity above corridor enclosure", "compartmentation"),
  cavitiesAdjacentToProtectedRouteFlag: boolFact("cavitiesAdjacentToProtectedRouteFlag", "Cavities adjacent to protected route", "compartmentation"),
  hasCavities: boolFact("hasCavities", "Has cavities", "compartmentation"),
  hasConcealedSpaces: boolFact("hasConcealedSpaces", "Has concealed spaces", "compartmentation"),
  cavityBarriersPresent: boolFact("cavityBarriersPresent", "Cavity barriers present", "compartmentation"),
  cavityBarriersPresentFlag: boolFact("cavityBarriersPresentFlag", "Cavity barriers present", "compartmentation"),
  cavityBarriersProvidedFlag: boolFact("cavityBarriersProvidedFlag", "Cavity barriers provided", "compartmentation"),
  cavityBarriersProvidedToProtectedRouteFlag: boolFact("cavityBarriersProvidedToProtectedRouteFlag", "Cavity barriers provided to protected route", "compartmentation"),
  cavityBarriersAroundOpeningsPresent: boolFact("cavityBarriersAroundOpeningsPresent", "Cavity barriers around openings present", "compartmentation"),
  cavityBarriersAroundOpeningFlag: boolFact("cavityBarriersAroundOpeningFlag", "Cavity barriers around opening", "compartmentation"),
  cavityBarrierPresent: boolFact("cavityBarrierPresent", "Cavity barrier present", "compartmentation"),
  cavityBarrierProvidedAroundOpening: boolFact("cavityBarrierProvidedAroundOpening", "Cavity barrier provided around opening", "compartmentation"),
  cavityBarrierLocationsCompliantFlag: boolFact("cavityBarrierLocationsCompliantFlag", "Cavity barrier locations compliant", "compartmentation"),
  cavityBarriersDivideCavities: boolFact("cavityBarriersDivideCavities", "Cavity barriers divide cavities", "compartmentation"),
  cavityBarriersCloseEdges: boolFact("cavityBarriersCloseEdges", "Cavity barriers close edges", "compartmentation"),
  cavityBarrierFixingSpecified: boolFact("cavityBarrierFixingSpecified", "Cavity barrier fixing specified", "compartmentation"),
  cavityBarrierFixingInstalled: boolFact("cavityBarrierFixingInstalled", "Cavity barrier fixing installed", "compartmentation"),
  cavityBarrierOpeningsPresent: boolFact("cavityBarrierOpeningsPresent", "Cavity barrier openings present", "compartmentation"),
  openingPresentInCavityEdge: boolFact("openingPresentInCavityEdge", "Opening present in cavity edge", "compartmentation"),
  openingsInCavityConstruction: boolFact("openingsInCavityConstruction", "Openings in cavity construction", "compartmentation"),
  openingPermitted: boolFact("openingPermitted", "Opening permitted", "compartmentation"),
  openingProtected: boolFact("openingProtected", "Opening protected", "compartmentation"),
  openingType: textFact("openingType", "Opening type", "compartmentation"),
  cavityLocation: textFact("cavityLocation", "Cavity location", "compartmentation"),
  cavityMaxDimensionM: numFact("cavityMaxDimensionM", "Cavity maximum dimension", "compartmentation", "m"),
  roofEdgeCavityBarrierRequired: boolFact("roofEdgeCavityBarrierRequired", "Roof edge cavity barrier required", "compartmentation"),
  roofEdgeCavityBarrierProvided: boolFact("roofEdgeCavityBarrierProvided", "Roof edge cavity barrier provided", "compartmentation"),

  structuralFramePresent: boolFact("structuralFramePresent", "Structural frame present", "compartmentation"),
  isLoadbearing: boolFact("isLoadbearing", "Is loadbearing", "compartmentation"),
  elementSupportsOther: boolFact("elementSupportsOther", "Element supports other", "compartmentation"),
  supportsOrStabilises: boolFact("supportsOrStabilises", "Supports or stabilises", "compartmentation"),
  supportOnlyRoof: boolFact("supportOnlyRoof", "Support only roof", "compartmentation"),
  structureSupportsOnlyRoof: boolFact("structureSupportsOnlyRoof", "Structure supports only roof", "compartmentation"),
  roofMemberIsStructuralStabilitySystem: boolFact("roofMemberIsStructuralStabilitySystem", "Roof member is structural stability system", "compartmentation"),
  newStoreyAdded: boolFact("newStoreyAdded", "New storey added", "compartmentation"),
  meansOfEscapeCompliantWithSection3: boolFact("meansOfEscapeCompliantWithSection3", "Means of escape compliant with section 3", "compartmentation"),

  specialHazardFlag: boolFact("specialHazardFlag", "Special hazard", "compartmentation"),
  specialFireHazardPresent: boolFact("specialFireHazardPresent", "Special fire hazard present", "compartmentation"),
  isSemiDetachedOrTerraced: boolFact("isSemiDetachedOrTerraced", "Semi-detached or terraced", "compartmentation"),
  separatingWallIsCompartmentWall: boolFact("separatingWallIsCompartmentWall", "Separating wall is compartment wall", "compartmentation"),
  partyWallPresentFlag: boolFact("partyWallPresentFlag", "Party wall present", "compartmentation"),
  hasAttachedOrIntegralGarage: boolFact("hasAttachedOrIntegralGarage", "Attached or integral garage present", "compartmentation"),
  hasDoorBetweenGarageAndDwelling: boolFact("hasDoorBetweenGarageAndDwelling", "Door between garage and dwelling", "compartmentation"),
  garageSeparationReiMinutes: numFact("garageSeparationReiMinutes", "Garage separation REI", "compartmentation", "minutes"),
  doorSmokeSealSa: boolFact("doorSmokeSealSa", "Door smoke seal Sa", "compartmentation"),
  doorSelfClosing: boolFact("doorSelfClosing", "Door self-closing", "compartmentation"),
  doorRating: textFact("doorRating", "Door rating", "compartmentation"),
  selfClosing: boolFact("selfClosing", "Self-closing", "compartmentation"),
  sealsCondition: textFact("sealsCondition", "Seals condition", "compartmentation"),

  pipePenetrationPresent: boolFact("pipePenetrationPresent", "Pipe penetration present", "compartmentation"),
  pipe_penetration_present: boolFact("pipe_penetration_present", "Pipe penetration present", "compartmentation"),
  pipeNominalInternalDiameterMM: numFact("pipeNominalInternalDiameterMM", "Pipe nominal internal diameter", "compartmentation", "mm"),
  pipe_nominal_internal_diameter_mm: numFact("pipe_nominal_internal_diameter_mm", "Pipe nominal internal diameter", "compartmentation", "mm"),
  pipeMaterial: textFact("pipeMaterial", "Pipe material", "compartmentation"),
  pipe_material: textFact("pipe_material", "Pipe material", "compartmentation"),
  pipeMaterialCategory: textFact("pipeMaterialCategory", "Pipe material category", "compartmentation"),
  table10_1Situation: textFact("table10_1Situation", "Table 10.1 situation", "compartmentation"),
  pipePenetrationsThroughFireSeparatingElementFlag: boolFact("pipePenetrationsThroughFireSeparatingElementFlag", "Pipe penetrations through fire-separating element", "compartmentation"),
  flueOrDuctThroughFireSeparatingElementFlag: boolFact("flueOrDuctThroughFireSeparatingElementFlag", "Flue or duct through fire-separating element", "compartmentation"),
  flueOrDuctContainingFluesPresentFlag: boolFact("flueOrDuctContainingFluesPresentFlag", "Flue or duct containing flues present", "compartmentation"),
  flueOrDuctPassesThroughOrBuiltIntoCompartmentElementFlag: boolFact("flueOrDuctPassesThroughOrBuiltIntoCompartmentElementFlag", "Flue or duct passes through or built into compartment element", "compartmentation"),
  flueOrDuctWallClassA1Flag: boolFact("flueOrDuctWallClassA1Flag", "Flue or duct wall Class A1", "compartmentation"),

  // ---------------------------------------------------------------------------
  // External fire spread / materials
  // ---------------------------------------------------------------------------
  claddingMaterial: textFact("claddingMaterial", "Cladding material", "external_fire"),
  externalWallSystem: textFact("externalWallSystem", "External wall system", "external_fire"),
  externalWallReactionToFireClass: textFact("externalWallReactionToFireClass", "External wall reaction to fire class", "external_fire"),
  relevantBuildingFlag: boolFact("relevantBuildingFlag", "Relevant building", "external_fire"),
  buildingIsRelevantFlag: boolFact("buildingIsRelevantFlag", "Building is relevant", "external_fire"),
  reg7AppliesFlag: boolFact("reg7AppliesFlag", "Regulation 7 applies", "external_fire"),
  becomesRelevantBuildingFlag: boolFact("becomesRelevantBuildingFlag", "Becomes relevant building", "external_fire"),
  materialChangeOfUseFlag: boolFact("materialChangeOfUseFlag", "Material change of use", "external_fire"),
  externalWallComponents: textFact("externalWallComponents", "External wall components", "external_fire"),
  externalWallAttachmentPresentFlag: boolFact("externalWallAttachmentPresentFlag", "External wall attachment present", "external_fire"),
  externalWallRoofJunction: boolFact("externalWallRoofJunction", "External wall roof junction", "external_fire"),
  hasCanopy: boolFact("hasCanopy", "Canopy present", "external_fire"),
  has_canopy: boolFact("has_canopy", "Canopy present", "external_fire"),
  canopyProvidedFlag: boolFact("canopyProvidedFlag", "Canopy provided", "external_fire"),
  measurementReferencePoint: textFact("measurementReferencePoint", "Measurement reference point", "external_fire"),
  roofConstructionType: textFact("roofConstructionType", "Roof construction type", "external_fire"),
  roofCoveringClassification: textFact("roofCoveringClassification", "Roof covering classification", "external_fire"),
  roofCoveringDesignation: textFact("roofCoveringDesignation", "Roof covering designation", "external_fire"),
  roofMaterial: textFact("roofMaterial", "Roof material", "external_fire"),
  roofCompartmentStrip1500ProvidedFlag: boolFact("roofCompartmentStrip1500ProvidedFlag", "Roof compartment strip 1500 provided", "external_fire"),
  roofCoveringBROOFT4In1500ZoneFlag: boolFact("roofCoveringBROOFT4In1500ZoneFlag", "Roof covering BROOF(t4) in 1500 zone", "external_fire"),
  roofDeckClassA2s3d2OrBetterIn1500ZoneFlag: boolFact("roofDeckClassA2s3d2OrBetterIn1500ZoneFlag", "Roof deck Class A2-s3,d2 or better in 1500 zone", "external_fire"),
  thermoplasticRooflightsWithin1500ZoneFlag: boolFact("thermoplasticRooflightsWithin1500ZoneFlag", "Thermoplastic rooflights within 1500 zone", "external_fire"),
  balconyPresent: boolFact("balconyPresent", "Balcony present", "external_fire"),
  balconyOrExternalProjection: boolFact("balconyOrExternalProjection", "Balcony or external projection", "external_fire"),
  balconyFireSpreadControlEvidence: textFact("balconyFireSpreadControlEvidence", "Balcony fire spread control evidence", "external_fire"),
  solarShadingInstalledFlag: boolFact("solarShadingInstalledFlag", "Solar shading installed", "external_fire"),
  solarShadingHeightAboveGroundM: numFact("solarShadingHeightAboveGroundM", "Solar shading height above ground", "external_fire", "m"),
  membranePresentFlag: boolFact("membranePresentFlag", "Membrane present", "external_fire"),
  membraneUsedInExternalWallFlag: boolFact("membraneUsedInExternalWallFlag", "Membrane used in external wall", "external_fire"),
  membraneAboveGroundFlag: boolFact("membraneAboveGroundFlag", "Membrane above ground", "external_fire"),
  membraneReactionClass: textFact("membraneReactionClass", "Membrane reaction class", "external_fire"),
  thermalBreaksPresentFlag: boolFact("thermalBreaksPresentFlag", "Thermal breaks present", "external_fire"),

  // ---------------------------------------------------------------------------
  // Management / documentation / misc
  // ---------------------------------------------------------------------------
  staffPresencePattern: enumFact("staffPresencePattern", "Staff presence pattern", "management", ["unsupervised", "supervised"]),
  adjacencyToEscapeRoutes: boolFact("adjacencyToEscapeRoutes", "Adjacent to escape routes", "management"),
  evacuationStrategy: enumFact("evacuationStrategy", "Evacuation strategy", "management", ["stay put", "simultaneous evacuation", "phased evacuation"]),
  relevantChangeOfUseFlag: boolFact("relevantChangeOfUseFlag", "Relevant change of use", "management"),
  fireSafetyHandoverPackProvided: boolFact("fireSafetyHandoverPackProvided", "Fire safety handover pack provided", "management"),
  buildingComplexityFlag: boolFact("buildingComplexityFlag", "Building complexity", "management"),
  fireSafetyStrategyProvided: boolFact("fireSafetyStrategyProvided", "Fire safety strategy provided", "management"),
  operationsMaintenanceProceduresProvided: boolFact("operationsMaintenanceProceduresProvided", "Operations and maintenance procedures provided", "management"),
  causeEffectMatrixProvided: boolFact("causeEffectMatrixProvided", "Cause and effect matrix provided", "management"),
  usesBS9991Clause73Flag: boolFact("usesBS9991Clause73Flag", "Uses BS 9991 clause 7.3", "management"),
  departureFromADBPara327Flag: boolFact("departureFromADBPara327Flag", "Departure from ADB para 3.27", "management"),
  chosenApproach: textFact("chosenApproach", "Chosen approach", "management"),
  workType: textFact("workType", "Work type", "management"),
  buildingOtherThanDwellingsFlag: boolFact("buildingOtherThanDwellingsFlag", "Building other than dwellings", "management"),
  measurementReferencePoint: textFact("measurementReferencePoint", "Measurement reference point", "management"),
  spaceSeparationAppliesFlag: boolFact("spaceSeparationAppliesFlag", "Space separation applies", "management"),
  unprotectedAreaCalcProvided: boolFact("unprotectedAreaCalcProvided", "Unprotected area calculation provided", "management"),

  // ---------------------------------------------------------------------------
  // Materials / linings / classification
  // ---------------------------------------------------------------------------
  liningClass: textFact("liningClass", "Lining class", "other"),
  lining_class: textFact("lining_class", "Lining class", "other"),
  liningClassification: textFact("liningClassification", "Lining classification", "other"),
  wallLiningClass: textFact("wallLiningClass", "Wall lining class", "other"),
  ceilingLiningClass: textFact("ceilingLiningClass", "Ceiling lining class", "other"),
  lowerPerformanceLiningClass: textFact("lowerPerformanceLiningClass", "Lower performance lining class", "other"),
  lowerPerformanceLiningAreaM2: numFact("lowerPerformanceLiningAreaM2", "Lower performance lining area", "other", "m2"),
  lowerPerfWallLiningClass: textFact("lowerPerfWallLiningClass", "Lower performance wall lining class", "other"),
  lowerPerfWallLiningPercentage: numFact("lowerPerfWallLiningPercentage", "Lower performance wall lining percentage", "other"),
  allowanceAppliedFlag: boolFact("allowanceAppliedFlag", "Allowance applied", "other"),
  hasGlazedCeiling: boolFact("hasGlazedCeiling", "Glazed ceiling present", "other"),
  ceilingTreatedAsLiningFlag: boolFact("ceilingTreatedAsLiningFlag", "Ceiling treated as lining", "other"),
  surfaceClassificationTreatedAsWallFlag: boolFact("surfaceClassificationTreatedAsWallFlag", "Surface classification treated as wall", "other"),
  liningClassificationAppliedFlag: boolFact("liningClassificationAppliedFlag", "Lining classification applied", "other"),
  elementType: textFact("elementType", "Element type", "other"),
  isCirculationSpace: boolFact("isCirculationSpace", "Is circulation space", "other"),

  componentType: textFact("componentType", "Component type", "other"),
  component_type: textFact("component_type", "Component type", "other"),
  materialClass: textFact("materialClass", "Material class", "other"),
  material_class: textFact("material_class", "Material class", "other"),
  rooflightTpClass: textFact("rooflightTpClass", "Rooflight TP class", "other"),
  rooflight_tp_class: textFact("rooflight_tp_class", "Rooflight TP class", "other"),
  rooflightMaterial: textFact("rooflightMaterial", "Rooflight material", "other"),
  thermoplastic: boolFact("thermoplastic", "Thermoplastic", "other"),
  thermoplasticPresent: boolFact("thermoplasticPresent", "Thermoplastic present", "other"),
  thermoplastic_present: boolFact("thermoplastic_present", "Thermoplastic present", "other"),
  thermoplasticClassLowerSurface: textFact("thermoplasticClassLowerSurface", "Thermoplastic class lower surface", "other"),
  diffuserFormsPartOfCeiling: boolFact("diffuserFormsPartOfCeiling", "Diffuser forms part of ceiling", "other"),
  diffuserThermoplasticClass: textFact("diffuserThermoplasticClass", "Diffuser thermoplastic class", "other"),
  diffusersThermoplasticFlag: boolFact("diffusersThermoplasticFlag", "Diffusers thermoplastic", "other"),
  diffuserClassification: textFact("diffuserClassification", "Diffuser classification", "other"),
  ceilingThermoplasticClass: textFact("ceilingThermoplasticClass", "Ceiling thermoplastic class", "other"),
  supportedOnAllSides: boolFact("supportedOnAllSides", "Supported on all sides", "other"),
  lightingDiffusersProvidedFlag: boolFact("lightingDiffusersProvidedFlag", "Lighting diffusers provided", "other"),
  lightingDiffusersFormPartOfCeilingConstructionFlag: boolFact("lightingDiffusersFormPartOfCeilingConstructionFlag", "Lighting diffusers form part of ceiling construction", "other"),
  surfacesAboveSuspendedCeilingComplyWithPara6_1Flag: boolFact("surfacesAboveSuspendedCeilingComplyWithPara6_1Flag", "Surfaces above suspended ceiling comply with para 6.1", "other"),

  // ---------------------------------------------------------------------------
  // Additional booleans / text to close common gaps
  // ---------------------------------------------------------------------------
  passengerLiftPresent: boolFact("passengerLiftPresent", "Passenger lift present", "other"),
  passengerLiftPresentFlag: boolFact("passengerLiftPresentFlag", "Passenger lift present", "other"),
  liftServesStoreyAbove4_5Flag: boolFact("liftServesStoreyAbove4_5Flag", "Lift serves storey above 4.5m", "other"),
  liftWithinProtectedStairEnclosureFlag: boolFact("liftWithinProtectedStairEnclosureFlag", "Lift within protected stair enclosure", "other"),
  liftInRei30ShaftFlag: boolFact("liftInRei30ShaftFlag", "Lift in REI 30 shaft", "other"),
  airCirculationSystemPresentFlag: boolFact("airCirculationSystemPresentFlag", "Air circulation system present", "other"),

  newHabitableRoomFlag: boolFact("newHabitableRoomFlag", "New habitable room", "other"),
  newHabitableRoomAboveGroundFlag: boolFact("newHabitableRoomAboveGroundFlag", "New habitable room above ground", "other"),
  newHabitableRoomBelowGroundFlag: boolFact("newHabitableRoomBelowGroundFlag", "New habitable room below ground", "other"),
  newHabitableRoomGroundStoreyFlag: boolFact("newHabitableRoomGroundStoreyFlag", "New habitable room at ground storey", "other"),
  groundStoreyHabitableHasFinalExitFlag: boolFact("groundStoreyHabitableHasFinalExitFlag", "Ground storey habitable room has final exit", "other"),

  openingType: textFact("openingType", "Opening type", "other"),
  openingPermitted: boolFact("openingPermitted", "Opening permitted", "other"),
  openingProtected: boolFact("openingProtected", "Opening protected", "other"),
  openingFireResistanceMin: numFact("openingFireResistanceMin", "Opening fire resistance", "other", "minutes"),
  openingSizeMinimised: boolFact("openingSizeMinimised", "Opening size minimised", "other"),
  openingsInShaftEnclosureFlag: boolFact("openingsInShaftEnclosureFlag", "Openings in shaft enclosure", "other"),

  usesWithinStairList: textFact("usesWithinStairList", "Uses within stair list", "other"),
  location: textFact("location", "Location", "other"),
  specialFireHazardPresent: boolFact("specialFireHazardPresent", "Special fire hazard present", "other"),
  isConversionToFlats: boolFact("isConversionToFlats", "Conversion to flats", "other"),
  existingConstructionReviewed: boolFact("existingConstructionReviewed", "Existing construction reviewed", "other"),
  exceptionClaimed: boolFact("exceptionClaimed", "Exception claimed", "other"),
  exceptionType: textFact("exceptionType", "Exception type", "other"),
  isExternalWindow: boolFact("isExternalWindow", "Is external window", "other"),
  isProtectedStairway: boolFact("isProtectedStairway", "Is protected stairway", "other"),

  // --- audit added keys ---
  escapeRouteCount: numFact("escapeRouteCount","Escape route count","escape"),
  combinedFlowRequiredFlag: boolFact("combinedFlowRequiredFlag","Combined flow required","escape"),
  spaceMaxOccupancy: numFact("spaceMaxOccupancy","Space max occupancy","occupancy"),
  numberExits: numFact("numberExits","Number of exits","escape"),
  protectedPowerCircuitRequired: boolFact("protectedPowerCircuitRequired","Protected power circuit required","other"),
  protectedPowerCircuitProvided: boolFact("protectedPowerCircuitProvided","Protected power circuit provided","other"),
  escapeRoutesSharedBetweenUsesFlag: boolFact("escapeRoutesSharedBetweenUsesFlag","Escape routes shared between uses","escape"),
  habitableRoomAccessPassesThroughAnotherRoomFlag: boolFact("habitableRoomAccessPassesThroughAnotherRoomFlag","Habitable room access passes through another room","escape"),
  bedroomsSeparatedFromLivingByREI30Flag: boolFact("bedroomsSeparatedFromLivingByREI30Flag","Bedrooms separated from living by REI30","other"),
  bedroomSeparationFireDoorsE20Flag: boolFact("bedroomSeparationFireDoorsE20Flag","Bedroom separation fire doors E20","other"),
  glazedScreenInShaftEnclosureFlag: boolFact("glazedScreenInShaftEnclosureFlag","Glazed screen in shaft enclosure","other"),
  carParkFlag: boolFact("carParkFlag","Car park","occupancy"),
  usingFireResistingCeilingAsStrategy: boolFact("usingFireResistingCeilingAsStrategy","Using fire resisting ceiling strategy","other"),
  ceilingIsImperforate: boolFact("ceilingIsImperforate","Ceiling imperforate","other"),
  bedroomPartitionNonFireResisting: boolFact("bedroomPartitionNonFireResisting","Bedroom partition non fire resisting","other"),
  cavityBarrierAboveOrBelowBedroomPartition: boolFact("cavityBarrierAboveOrBelowBedroomPartition","Cavity barrier above or below bedroom partition","other"),
  penetrationsSmokeSealed: boolFact("penetrationsSmokeSealed","Penetrations smoke sealed","other"),
  insulationContactsBothSkins: boolFact("insulationContactsBothSkins","Insulation contacts both skins","other"),
  hasCompartmentWallToRoofJunction: boolFact("hasCompartmentWallToRoofJunction","Compartment wall to roof junction","other"),
  topFloorHeightM: numFact("topFloorHeightM","Top floor height","building","m"),
  topFloorHeight_m: numFact("topFloorHeight_m","Top floor height","building","m"),
  isLoftConversion: boolFact("isLoftConversion","Loft conversion","building"),
  hasBasement: boolFact("hasBasement","Basement present","building"),
  naturalSmokeOutletAreaM2: numFact("naturalSmokeOutletAreaM2","Natural smoke outlet area","smoke","m2"),
  mechanicalSmokeExtractRate: numFact("mechanicalSmokeExtractRate","Mechanical smoke extract rate","smoke"),
  flatToCorridorWallFireResistanceMinutes: numFact("flatToCorridorWallFireResistanceMinutes","Flat to corridor wall FR","other","minutes"),

};

export function getFactDefinition(key: string): FactDefinition | undefined {
  return FACT_ONTOLOGY[key];
}

export function allFactKeys(): string[] {
  return Object.keys(FACT_ONTOLOGY);
}
